spring.application.name=discovery-service
server.port=8761

# Eureka Server runs standalone and does not register as a Eureka client instance.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost

eureka.server.enable-self-preservation=false
